# Generated by Django 2.0.2 on 2018-02-28 14:17

# Third Party Libraries
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='motif',
            field=models.CharField(max_length=60),
        ),
    ]
