# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2018-03-16 18:07
from __future__ import unicode_literals

from pony import orm
from pony.migrate import diagram_ops as op

dependencies = ['0001_initial']

operations = [
    op.AddAttr('Patient', 'street', orm.Optional(str, sql_default="''"))]
