# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2018-03-16 19:18
from __future__ import unicode_literals

from pony import orm
from pony.migrate import diagram_ops as op

dependencies = ['0003_2018-03-16_18-29-37']

operations = [
    op.ModifyAttr('Patient', 'street', orm.Optional(str))]
