# Generated by Django 2.0.2 on 2018-02-05 11:29

# Third Party Libraries
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('sexe', models.BooleanField(default=True)),
                ('street', models.CharField(blank=True, default='', max_length=200)),
                ('postalcode', models.CharField(blank=True, default='', max_length=5)),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('phonenumber', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
    ]
